name: todakmore
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3
  sign_in_with_apple: ^7.0.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  path: ^1.9.1
  photo_manager: ^3.8.2
  equatable: ^2.0.7
  uuid: ^4.5.2
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#EFE8FF"
  android_12:
    color: "#EFE8FF"

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/img/g-logo.png
    - assets/img/kakao_bubble.png
    - assets/icon/splash_icon.png

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 600
    - family: Cafe24Ssukssuk
      fonts:
        - asset: assets/fonts/Cafe24Ssukssuk-v2.0.ttf