name: todakmore
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3
  sign_in_with_apple: ^7.0.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/img/g-logo.png
    - assets/img/kakao_bubble.png

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 600
    - family: Cafe24Ssukssuk
      fonts:
        - asset: assets/fonts/Cafe24Ssukssuk-v2.0.ttf